package com.melnyk.tasks;

import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class Task3 {

  private List<Integer> getList1() {
    System.out.println("Generated by Array.asList():");
    return Arrays.asList(2, 4, 9, 1, 7, 61, 3, 64, 46, 52);
  }

  private List<Integer> getList2() {
    System.out.println("Generated by Stream.generate():");
    Random random = new Random();
    return Stream
        .generate(() -> random.nextInt(100)).limit(10)
        .collect(Collectors.toList());
  }

  private List<Integer> getList3() {
    System.out.println("Generated by Stream.of():");
    return Stream.of(1, 45, 7, 8, 49, 45, 82, 62, 48, 46)
        .collect(Collectors.toList());
  }

  private List<Integer> getList4() {
    System.out.println("Generated by Stream.iterate():");
    return Stream.iterate(1, x -> x + 3).limit(10)
        .collect(Collectors.toList());
  }

  public void getTask3() {
    List<Integer> list = getList1();
    list.forEach(x -> System.out.print(x + " "));
    System.out.println("\nAverage of numbers: " + list.stream()
        .mapToInt(x -> x).average().getAsDouble() + "\n");

    list = getList2();
    list.forEach(x -> System.out.print(x + " "));
    System.out.println("\nMin of numbers: " + list.stream()
        .min(Comparator.comparingInt(Integer::intValue)).get() + "\n");

    list = getList3();
    list.forEach(x -> System.out.print(x + " "));
    System.out.println("\nMax of numbers: " + list.stream()
        .max(Comparator.comparingInt(Integer::intValue)).get() + "\n");

    list = getList4();
    list.forEach(x -> System.out.print(x + " "));
    System.out.println("\nSum of numbers by mapToInt().sum: " + list.stream()
        .mapToInt(x -> x).sum() + "\n");

    list = getList1();
    list.forEach(x -> System.out.print(x + " "));
    System.out.println("\nSum of numbers by reduce(): " + list.stream()
        .reduce((a, b) -> b += a).get() + "\n");

    List<Integer> finalList = getList2();
    finalList.forEach(x -> System.out.print(x + " "));
    System.out.println("\nAverage of numbers: " + finalList.stream()
        .mapToInt(x -> x).average().getAsDouble());
    List<Integer> filteredList = finalList.stream()
        .filter(x -> x > finalList.stream().mapToInt(y -> y)
            .average().getAsDouble()).collect(Collectors.toList());
    System.out.print("Number of values that are bigger than average: ");
    System.out.println(filteredList.stream().count());
  }
}
